### ISSUE TITLE
KO rule not working

### ISSUE THREAD

**Issue by aertoria** [lys1030/ng-go#4]

**Comment by aesth0x** [comment]
Sorry for closing this issue, as it's a duplication of issue #3.

**Comment by aertoria** [comment]
It's a nice project. did you start it from scratch?

Ethan

On April 3, 2016 at 4:54:46 PM, Yongsheng Li (notifications@github.com) wrote:

Closed #4.

**Comment by aesth0x** [comment]
Yes, from scratch. I just want to try and get familiar with Angular 2 as it comes to beta.
